### ISSUE TITLE
missing binaries do not create date?

### ISSUE THREAD

**Issue by lorenzog** [gchers/p#1]
On a Debian 8 system (Qubes OS template), where I forgot to install `xclip` I get some odd messages.

Note that `lib/p` is where I cloned the git repo.

```
$ lib/p/p.sh -a foo
password (empty to generate one): 
lib/p/p.sh: line 44: md5: command not found
lib/p/p.sh: line 99: xclip: command not found
[*] password added

```

Notice: in Linux the utility is called `md5sum` not `md5`. Perhaps add a configuration variable to invoke another hash function e.g. sha256sum?

Then:

```
$ gpg -d .p/store.gpg 
gpg: encrypted with 2048-bit RSA key, ID D1166F50, created 2016-08-26
      "pmanager"
foo  1472251318

```

But

```
$ lib/p/p.sh -l
gpg: encrypted with 2048-bit RSA key, ID D1166F50, created 2016-08-26
      "pmanager"
label   age
--------------
lib/p/p.sh: line 37: let: days=(1472251431-)/86400: syntax error: operand expected (error token is ")/86400")
foo 

```

**Comment by gchers** [comment]
Thank you. Commits 7091b67 to 2264991 should fix (sorry for not creating a PR for making the changes more obvious).
