### ISSUE TITLE
Misleading LOC

### ISSUE THREAD

**Issue by peperunas** [gchers/p#5]
The project is more than 200 lines of bash. Misleading.

**Comment by gchers** [comment]
Dear @peperunas,

Thank you indeed for raising this matter. At `p`, we take these allegations extremely seriously.

From my calculations, if we are to exclude any line that is either empty or is a comment, we get:

```sh
$ grep -v -e '^#' -e '^$' -e '^[ ]*#' p.sh | wc -l
184
```

This is less than 200 LoC, as advertised.

Kind regards,

:rofl:
